source("read_hpc.R")
png("plot4.png", width=480, height=480)
data<- read_hpc()
par(mfrow=c(2,2))
plot(data$Time,data$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(data$Time, data$Voltage, xlab="dateTime", ylab="Voltage", type="l")
plot(data$Time, data$Sub_metering_1, type="l", col="black",
     xlab="", ylab="Energy sub metering")
lines(data$Time, data$Sub_metering_2, col="red")
lines(data$Time, data$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black", "red","blue"), lty=1, bty="n")
plot(data$Time,data$Global_reactive_power, type="l", xlab="dateTime")
dev.off()